spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xww_db02
    username: root
    password: xww
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    hiddenmethod:
      filter:
        enabled: true
